### ISSUE TITLE
Error in workflow: 'display_priority'

### ISSUE THREAD

**Issue by conformist1** [vinaywadhwa/justwatch-alfred#7]
![Screen Shot 2020-12-19 at 3 59 13 PM](https://user-images.githubusercontent.com/46271586/102702074-3d963c80-4213-11eb-88d5-2e74c4f05be4.png)
(changed 'justwatch' to watch)

Getting this error even after updating to 1.0.7

Any ideas?

System info:
MacOS 10.15.7
Alfred 4.3 [1205]

**Comment by vinaywadhwa** [comment]
Thanks so much for the report. This is now fixed in version 1.0.8. 

The error was due to something changing in the underlying API this workflow uses. 

The workflow will prompt you for an update (automatically) the next time you use it. You can also manually download and install the newer version yourself 😅 

Cheers!

**Comment by conformist1** [comment]
@vinaywadhwa I wasn't prompted for an automatic update but had success updating from this repo.
